### ISSUE TITLE
CancellationTokenSource support in Tasks

### ISSUE THREAD

**Issue by bogdoslav** [jbruening/unity3d-extensions#2]
Hello! Please add support of CancellationTokenSource.
I would like to use 
https://github.com/Impyy/SharpTox in unity. 

Thank you in advance!

**Comment by jbruening** [comment]
So looking into it a bunch, and I found AsyncBridge, which supports async/await and Tasks in 3.5, so long as you're compiling it into a dll in visual studio. I've already tested, somewhat with the dispatcher thing I just added, and they work just fine.  Use the AsyncBridge 3.5 nuget package.
